# vtzb_proxy configuration file
#
# ============================================================================
# VM Socket Configuration
# ============================================================================

# max_vm_count: Maximum number of VMs supported
# This defines the maximum number of concurrent VMs that can connect.
# Range: 1-64
# Default: 64
#
max_vm_count = 64

# ============================================================================
# NUMA CPU Binding Configuration
# ============================================================================
#
# Supported formats(cpu cores)：
# - Single CPU: "0", "1", "2"
# - CPU list: "0,1,2,3"
# - CPU range: "0-3"
# - Mixed format: "0,22-48,6"
#
# Default: last 8 cpu cores

numa_bindings = 8-15

# ============================================================================
# vpuset map Configuration
# ============================================================================
#
# Map the ta_cpu_set to the set of physical CPUs bound to the corresponding vCPUs.
# Defaluts if omiited.
#
# legal value(Case-insensitive):
#   true
#   false
#
# Default: true

use_vcpuset = true