# This kernel module can be automatically loaded by user when TEE function need to be use in virtual machine.
# Remove the blacklist by adding a comment # at the start of the line.
blacklist vtzdriver